// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SpeechBasedGroceries.Parties.Fridgy.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BaseProduct
    {
        /// <summary>
        /// Initializes a new instance of the BaseProduct class.
        /// </summary>
        public BaseProduct()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BaseProduct class.
        /// </summary>
        /// <param name="qtyType">Possible values include: 'gramm',
        /// 'milliliter', 'pieces'</param>
        public BaseProduct(string name = default(string), string description = default(string), string barcode = default(string), long? qty = default(long?), string qtyType = default(string), string imgurl = default(string), BaseProductNutrient nutrient = default(BaseProductNutrient))
        {
            Name = name;
            Description = description;
            Barcode = barcode;
            Qty = qty;
            QtyType = qtyType;
            Imgurl = imgurl;
            Nutrient = nutrient;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "barcode")]
        public string Barcode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "qty")]
        public long? Qty { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'gramm', 'milliliter',
        /// 'pieces'
        /// </summary>
        [JsonProperty(PropertyName = "qty_type")]
        public string QtyType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "imgurl")]
        public string Imgurl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nutrient")]
        public BaseProductNutrient Nutrient { get; set; }

    }
}
