// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SpeechBasedGroceries.Parties.Fridgy.Client.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BaseItem
    {
        /// <summary>
        /// Initializes a new instance of the BaseItem class.
        /// </summary>
        public BaseItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BaseItem class.
        /// </summary>
        public BaseItem(string barcode, double qty, System.DateTime? expiry = default(System.DateTime?))
        {
            Barcode = barcode;
            Expiry = expiry;
            Qty = qty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "barcode")]
        public string Barcode { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "expiry")]
        public System.DateTime? Expiry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "qty")]
        public double Qty { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Barcode == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Barcode");
            }
        }
    }
}
