// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SpeechBasedGroceries.Parties.Fridgy.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateProduct : BaseProduct
    {
        /// <summary>
        /// Initializes a new instance of the CreateProduct class.
        /// </summary>
        public CreateProduct()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateProduct class.
        /// </summary>
        /// <param name="qtyType">Possible values include: 'gramm',
        /// 'milliliter', 'pieces'</param>
        public CreateProduct(string category, string name = default(string), string description = default(string), string barcode = default(string), long? qty = default(long?), string qtyType = default(string), string imgurl = default(string), BaseProductNutrient nutrient = default(BaseProductNutrient))
            : base(name, description, barcode, qty, qtyType, imgurl, nutrient)
        {
            Category = category;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Category == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Category");
            }
        }
    }
}
