// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SpeechBasedGroceries.Parties.Fridgy.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Fridge : BaseFridge
    {
        /// <summary>
        /// Initializes a new instance of the Fridge class.
        /// </summary>
        public Fridge()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Fridge class.
        /// </summary>
        public Fridge(string name = default(string), IList<PublicUser> owner = default(IList<PublicUser>), PublicUser creator = default(PublicUser))
            : base(name)
        {
            Owner = owner;
            Creator = creator;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public IList<PublicUser> Owner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "creator")]
        public PublicUser Creator { get; set; }

    }
}
