// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SpeechBasedGroceries.Parties.Fridgy.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Owner
    {
        /// <summary>
        /// Initializes a new instance of the Owner class.
        /// </summary>
        public Owner()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Owner class.
        /// </summary>
        public Owner(System.Guid? uuid = default(System.Guid?))
        {
            Uuid = uuid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uuid")]
        public System.Guid? Uuid { get; set; }

    }
}
