// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SpeechBasedGroceries.Parties.Fridgy.Client.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Paths1qz8pmtfridgesUuidItemsItemUuidputrequestbodycontentapplicationJsonschema
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Paths1qz8pmtfridgesUuidItemsItemUuidputrequestbodycontentapplicationJsonschema
        /// class.
        /// </summary>
        public Paths1qz8pmtfridgesUuidItemsItemUuidputrequestbodycontentapplicationJsonschema()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// Paths1qz8pmtfridgesUuidItemsItemUuidputrequestbodycontentapplicationJsonschema
        /// class.
        /// </summary>
        public Paths1qz8pmtfridgesUuidItemsItemUuidputrequestbodycontentapplicationJsonschema(System.DateTime? expiry = default(System.DateTime?), double? qty = default(double?))
        {
            Expiry = expiry;
            Qty = qty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "expiry")]
        public System.DateTime? Expiry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "qty")]
        public double? Qty { get; set; }

    }
}
