// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SpeechBasedGroceries.Parties.Fridgy.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PostUser
    {
        /// <summary>
        /// Initializes a new instance of the PostUser class.
        /// </summary>
        public PostUser()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PostUser class.
        /// </summary>
        public PostUser(string username = default(string), string email = default(string), string password = default(string), string displayname = default(string))
        {
            Username = username;
            Email = email;
            Password = password;
            Displayname = displayname;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayname")]
        public string Displayname { get; set; }

    }
}
