// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SpeechBasedGroceries.Parties.Fridgy.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Product : BaseProduct
    {
        /// <summary>
        /// Initializes a new instance of the Product class.
        /// </summary>
        public Product()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Product class.
        /// </summary>
        /// <param name="qtyType">Possible values include: 'gramm',
        /// 'milliliter', 'pieces'</param>
        public Product(string name = default(string), string description = default(string), string barcode = default(string), long? qty = default(long?), string qtyType = default(string), string imgurl = default(string), BaseProductNutrient nutrient = default(BaseProductNutrient), System.Guid? id = default(System.Guid?), string creator = default(string), Category category = default(Category))
            : base(name, description, barcode, qty, qtyType, imgurl, nutrient)
        {
            Id = id;
            Creator = creator;
            Category = category;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "creator")]
        public string Creator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public Category Category { get; set; }

    }
}
