// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SpeechBasedGroceries.Parties.Fridgy.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PublicUser
    {
        /// <summary>
        /// Initializes a new instance of the PublicUser class.
        /// </summary>
        public PublicUser()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PublicUser class.
        /// </summary>
        public PublicUser(System.Guid? uuid = default(System.Guid?), string displayname = default(string))
        {
            Uuid = uuid;
            Displayname = displayname;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uuid")]
        public System.Guid? Uuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayname")]
        public string Displayname { get; set; }

    }
}
