// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SpeechBasedGroceries.Parties.Fridgy.Client
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// This is the API endpoint documentation from the Fridgy web app.
    /// </summary>
    public partial interface IFridgy : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IGet.
        /// </summary>
        IGet Get { get; }

        /// <summary>
        /// Gets the IUpdate.
        /// </summary>
        IUpdate Update { get; }

        /// <summary>
        /// Gets the IDelete.
        /// </summary>
        IDelete Delete { get; }

        /// <summary>
        /// Gets the ICreate.
        /// </summary>
        ICreate Create { get; }

        /// <summary>
        /// Gets the IAdd.
        /// </summary>
        IAdd Add { get; }

    }
}
