// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SpeechBasedGroceries.Parties.Fridgy.Client
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Update operations.
    /// </summary>
    public partial interface IUpdate
    {
        /// <summary>
        /// Update an existing product
        /// </summary>
        /// <param name='body'>
        /// Product object that needs to be updated
        /// </param>
        /// <param name='barcode'>
        /// Barcode used as unique identifier to find product
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<Product>> ProductsWithHttpMessagesAsync(CreateProduct body, string barcode, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Updates an existing item in a fridge identified by UUID
        /// </summary>
        /// <param name='uuid'>
        /// UUID to identify a fridge
        /// </param>
        /// <param name='itemUuid'>
        /// UUID of item
        /// </param>
        /// <param name='body'>
        /// Updated item.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<Item>> ItemMethodWithHttpMessagesAsync(string uuid, string itemUuid, Paths1qz8pmtfridgesUuidItemsItemUuidputrequestbodycontentapplicationJsonschema body = default(Paths1qz8pmtfridgesUuidItemsItemUuidputrequestbodycontentapplicationJsonschema), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
